version: "3.8"

x-go-service: &go-service
#  command: ["./bin/$${APP}", "-c", "./configs/$${APP}/config.yaml"]
  depends_on:
    - db
    - migrator
    - redis
  image: golang:1.17
  restart: always
  volumes:
    - ./bin:/app/bin
    - ./doc:/app/doc
    - ./configs:/app/configs
  working_dir: /app
  stop_signal: SIGTERM

services:
  client_gateway_service:
    <<: *go-service
    command: ["./bin/client_gateway_service", "-c", "./configs/client_gateway_service/config.yaml"]
    environment:
      APP: client_gateway_service
      LOG_LEVEL: 5
    ports:
      - 8080:80

  nsi_service:
    <<: *go-service
    command: ["./bin/nsi_service", "-c", "./configs/nsi_service/config.yaml"]
    environment:
      APP: nsi_service
      LOG_LEVEL: 5
    depends_on:
      - db_manager_service
    ports:
      - 8081:80

  db_manager_service:
    <<: *go-service
    command: ["./bin/db_manager_service", "-c", "./configs/db_manager_service/config.yaml"]
    environment:
      APP: db_manager_service
      LOG_LEVEL: 5
    ports:
      - 8082:80

  client_sso_service:
    <<: *go-service
    command: ["./bin/client_sso_service", "-c", "./configs/client_sso_service/config.yaml"]
    environment:
      APP: client_sso_service
      LOG_LEVEL: 5
    ports:
      - 8083:80

  review_media_storage_service:
    <<: *go-service
    command: ["./bin/review_media_storage_service", "-c", "./configs/review_media_storage_service/config.yaml"]
    environment:
      APP: review_media_storage_service
      LOG_LEVEL: 5
    ports:
      - 8084:80

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: cafe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]

  migrator:
    build:
      args:
        MIGRATION_DIR_ARG: migrations
        MIGRATION_TARGET_DIR_ARG: migrations
      context: .
      dockerfile: build/docker/migrator/Dockerfile
    command: >
      ./wait-for-pg.sh db 5432 cafe postgres postgres
      sql-migrate up -config=dbconfig.yml
    depends_on:
      - db
    volumes:
      - ./dbconfig.yml:/app/dbconfig.yml
      - ./migrations:/app/migrations
      - ./scripts/wait-for-pg.sh:/app/wait-for-pg.sh
    working_dir: /app

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

networks:
  default:
    driver: bridge

volumes:
  pgdata: