---
listen: :80

docPath: /app/doc

sentry_dsn: ""
sentry_env: localhost

logger:
  defaultchannel: stack
  level: ${LOG_LEVEL}
logChannels:
  stack:
    driver: stack
    extra:
      channels:
        - name: stderr
  stderr:
    driver: zap

db_manager_url: http://db_manager_service/v1

wp:
  check_db_period: 20s
  worker_amount: 4